@startuml
title SQLAlchemy ER snapshot
left to right direction
skinparam linetype ortho
hide methods
entity "items" as T_eef6af467d783cb824f428570042690ffd9567294e13e0c84c463dc4b049e875 {
  column id : integer type=builtins_U002E_int type_parameters=- nullable=? primary_key=? unique=? index=? default=- server_default=- onupdate=- server_onupdate=- computed=- identity=-
}
legend right
  rule_version=code-structure-viz.sqlalchemy-redaction/v1
  redacted_values=0
  --> foreign_key
  ..> relationship
  --|> inheritance
  -- association table
  [redacted] literal/expression value omitted
endlegend
@enduml
