@startuml
title SQLAlchemy ER snapshot
left to right direction
skinparam linetype ortho
hide methods
entity "admins" as T_57faa9e90ee93a98e8877c096c4f14db031bbfd49031393dd61be85c559d8db6 {
  inheritance target=users
}
entity "groups" as T_5d02309714b825412e9e807bb28666f29124761cdb410ea6a492faaa177859c6 {
  column id : integer type=builtins_U002E_int type_parameters=- nullable=? primary_key=true unique=? index=? default=- server_default=- onupdate=- server_onupdate=- computed=- identity=-
  primary_key <unnamed> columns=id
  relationship users target=users cardinality=many uselist=? back_populates=groups secondary=- primaryjoin=- secondaryjoin=- order_by=- foreign_keys=-
}
entity "membership" as T_fa837719b503ae5e50dc1e77df2b09e0c4a60f1aa73d54eca249701c3cf4c6fb {
  column id : integer type=sqlalchemy_U002E_Integer type_parameters=- nullable=? primary_key=? unique=? index=? default=- server_default=- onupdate=- server_onupdate=- computed=- identity=-
  association_table groups source=users target=groups relationship_member=441e077eb50d8cf00e9998dbbf1808ffa71910588f21e9e92cd4d9378098a94c
}
entity "users" as T_4ab4c2460e66df4965592a3108f1ea39ef7ddfd4790dc63806d4830019270515 {
  column id : integer type=builtins_U002E_int type_parameters=- nullable=? primary_key=true unique=? index=? default=- server_default=- onupdate=- server_onupdate=- computed=- identity=-
  primary_key <unnamed> columns=id
  relationship groups target=groups cardinality=many uselist=? back_populates=users secondary=membership primaryjoin=[redacted:sql_expression] secondaryjoin=- order_by=- foreign_keys=[redacted:literal]
}
T_4ab4c2460e66df4965592a3108f1ea39ef7ddfd4790dc63806d4830019270515 ..> T_5d02309714b825412e9e807bb28666f29124761cdb410ea6a492faaa177859c6 : relationship groups
T_4ab4c2460e66df4965592a3108f1ea39ef7ddfd4790dc63806d4830019270515 -- T_fa837719b503ae5e50dc1e77df2b09e0c4a60f1aa73d54eca249701c3cf4c6fb : association groups
T_57faa9e90ee93a98e8877c096c4f14db031bbfd49031393dd61be85c559d8db6 --|> T_4ab4c2460e66df4965592a3108f1ea39ef7ddfd4790dc63806d4830019270515 : inheritance
T_5d02309714b825412e9e807bb28666f29124761cdb410ea6a492faaa177859c6 ..> T_4ab4c2460e66df4965592a3108f1ea39ef7ddfd4790dc63806d4830019270515 : relationship users
legend right
  rule_version=code-structure-viz.sqlalchemy-redaction/v1
  redacted_values=2
  --> foreign_key
  ..> relationship
  --|> inheritance
  -- association table
  [redacted] literal/expression value omitted
endlegend
@enduml
